--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MagicGames-Network/VPNProtect
build-by-default: true
branches:
- main
projects:
  VPNProtect:
    path: VPNProtect/
    libs:
      - src: MagicGames-Network/VPNProtect/libVPN
        version: ^1.0.0
  libVPN:
    path: libVPN/
    model: virion
    type: library
...
