main: AGTHARN\VPNProtect\Main
name: VPNProtect
version: 2.0.1
author: AGTHARN
api: 4.0.0

permissions:
  vpnprotect.bypass:
    description: VPN Checks would not be run on players with this permission
    default: false
